### PR TITLE
6) Complete merging the decoder

### PR DESCRIPTION
**Pull request by abukharmeh**
Finishes merging the decoder. 

Not much changes in this PR apart from removing couple of redundant checks legacy of the old decoder. Initially, it was like this as I was running formal while moving every quadrant.

When reviewing this PR, I advise to look at it with ignore white space changes option on, as a a lot of the indentations where changed, but not much code.

### CODE REVIEW

**Comment by abukharmeh** [comment]
@davideschiavone Hi Davide, could you please have a look at this one ?

**Review by davideschiavone — APPROVED** [review]
really nice! pointing to @Silabs-ArjanB in case he is interested in evaluating it in the E40S and E40X cores.

@abukharmeh, can you pls push the sequential equivalent checking script? so that I can use it to check it the core still compiles and work? I know you check too, but if we are 2 it's less likely we forget anything

**Comment by abukharmeh** [comment]
Sorry for delaying that, I actually got green-light that we can release that, but didn't put it through the system yet, will do soon.

**Comment by davideschiavone** [comment]
thanks @abukharmeh

**Pull request merged**
